FROM apache/airflow:3.1.2-python3.12

USER root
RUN apt-get update && apt-get install -y \
    vim less curl \
 && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements/requirements_3_1_2.txt /requirements_3_1_2.txt
RUN pip install --no-cache-dir -r /requirements_3_1_2.txt || true
